version: '3.7'

services:
  currency-exchange:
    image: misssg85/currency-exchange:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
networks:
  currency-network: